// In-chat draft-journal tool for Mark's /qa.
//
// Mark calls `create_draft_manual_journal` ONLY after the user has typed an
// explicit YES confirming the lines he proposed in his prior turn. The tool
// posts to the reconciliation agent's /api/journals/draft with Bearer
// HUB_API_KEY + x-triggered-by: user:<basic-auth-name>. Status is hard-
// locked DRAFT at the recon write helper — there's no path here that can
// flip a draft to POSTED.
//
// The chat /qa flow ends up calling the Anthropic API twice per turn when
// the tool fires: once to get the tool_use, once to get the natural-language
// reply after we feed back the tool_result. The user sees one assistant
// message containing Mark's "✓ Draft created in Xero" confirmation + the
// deep-link.

import Anthropic from "@anthropic-ai/sdk";
import { env } from "../env";

export const CREATE_DRAFT_MANUAL_JOURNAL_TOOL: Anthropic.Messages.Tool = {
  name: "create_draft_manual_journal",
  description:
    "Create a DRAFT manual journal in Xero via the reconciliation agent. " +
    "STATUS IS HARD-LOCKED TO DRAFT — there is no path for the agent to flip " +
    "a draft to POSTED. The draft appears in Xero's drafts list awaiting " +
    "human review; Nicole / Tony / the external accountant clicks Post the " +
    "normal way.\n\n" +
    "ONLY CALL THIS TOOL after the user has typed an explicit YES (or 'yes', " +
    "'yes do it', 'go ahead', 'create it', 'create the draft') confirming the " +
    "lines you proposed in YOUR prior assistant turn. If the user hasn't " +
    "confirmed yet, propose the lines in plain text and ASK for confirmation " +
    "— do NOT call this tool.\n\n" +
    "Total DR must equal total CR exactly (within 1 cent). At least 2 lines " +
    "required. The narration appears in Xero and is auto-suffixed with a " +
    "'DRAFT — auto-generated' tag so reviewers know where it came from.",
  input_schema: {
    type: "object",
    properties: {
      entity: {
        type: "string",
        enum: ["SC", "CQ"],
        description: "SC (Sunshine Coast Pty Ltd) or CQ (Central Queensland Pty Ltd).",
      },
      narration: {
        type: "string",
        description:
          "Human-readable narration. Will appear in Xero's drafts list. The " +
          "agent auto-suffixes a 'DRAFT — auto-generated by JBC Reconciliation " +
          "Agent on <Brisbane ts>' tag so reviewers know where it came from.",
      },
      date: {
        type: "string",
        description:
          "yyyy-mm-dd journal date. Defaults to today (Brisbane) if omitted.",
      },
      lines: {
        type: "array",
        description: "Balanced DR/CR lines. Total DR must equal total CR.",
        items: {
          type: "object",
          properties: {
            amount: { type: "number", description: "Positive AUD amount." },
            side: { type: "string", enum: ["DR", "CR"] },
            accountCode: { type: "string", description: "Xero account code." },
            description: { type: "string", description: "Optional per-line description shown in Xero." },
          },
          required: ["amount", "side", "accountCode"],
        },
      },
      lineAmountTypes: {
        type: "string",
        enum: ["Exclusive", "Inclusive", "NoTax"],
        description: "Defaults to NoTax.",
      },
    },
    required: ["entity", "narration", "lines"],
  },
};

export interface DraftToolInput {
  entity?: unknown;
  narration?: unknown;
  date?: unknown;
  lines?: unknown;
  lineAmountTypes?: unknown;
}

export interface DraftToolResult {
  ok: boolean;
  manualJournalId?: string;
  xeroLink?: string;
  writeLogId?: string;
  triggeredBy?: string;
  error?: string;
  /** Echoed so Claude's follow-up reply has the numbers without re-deriving. */
  totalDr?: number;
  totalCr?: number;
}

/** Execute the create_draft_manual_journal tool — POSTs to recon's
 *  /api/journals/draft with Bearer HUB_API_KEY + x-triggered-by. Returns
 *  a JSON-serialisable result for the model's tool_result follow-up. */
export async function executeCreateDraftTool(args: {
  input: DraftToolInput;
  triggeredBy: string;
}): Promise<DraftToolResult> {
  // Validate the tool input before forwarding so failures surface cleanly
  // back to the model (it can apologise + ask the user to clarify).
  const entity = typeof args.input.entity === "string" ? args.input.entity.toUpperCase() : "";
  if (entity !== "SC" && entity !== "CQ") {
    return { ok: false, error: `entity must be 'SC' or 'CQ' — got '${entity}'` };
  }
  const narration = typeof args.input.narration === "string" ? args.input.narration.trim() : "";
  if (!narration) return { ok: false, error: "narration required" };

  const date = typeof args.input.date === "string" && /^\d{4}-\d{2}-\d{2}$/.test(args.input.date)
    ? args.input.date
    : undefined;

  const lineAmountTypes =
    args.input.lineAmountTypes === "Exclusive"
      || args.input.lineAmountTypes === "Inclusive"
      || args.input.lineAmountTypes === "NoTax"
      ? args.input.lineAmountTypes
      : undefined;

  if (!Array.isArray(args.input.lines) || args.input.lines.length < 2) {
    return { ok: false, error: "at least 2 lines required" };
  }
  const lines: Array<{ amount: number; side: "DR" | "CR"; accountCode: string; description?: string }> = [];
  let totalDr = 0;
  let totalCr = 0;
  for (let i = 0; i < args.input.lines.length; i++) {
    const raw = args.input.lines[i] as { amount?: unknown; side?: unknown; accountCode?: unknown; description?: unknown };
    const amount = typeof raw.amount === "number" ? raw.amount : Number(raw.amount);
    if (!Number.isFinite(amount) || amount <= 0) {
      return { ok: false, error: `lines[${i}].amount must be a positive number` };
    }
    if (raw.side !== "DR" && raw.side !== "CR") {
      return { ok: false, error: `lines[${i}].side must be 'DR' or 'CR'` };
    }
    if (typeof raw.accountCode !== "string" || !raw.accountCode.trim()) {
      return { ok: false, error: `lines[${i}].accountCode required` };
    }
    if (raw.side === "DR") totalDr += amount;
    else totalCr += amount;
    lines.push({
      amount,
      side: raw.side,
      accountCode: raw.accountCode.trim(),
      description: typeof raw.description === "string" ? raw.description : undefined,
    });
  }
  if (Math.abs(totalDr - totalCr) > 0.01) {
    return {
      ok: false,
      error: `unbalanced: DR ${totalDr.toFixed(2)} != CR ${totalCr.toFixed(2)}`,
      totalDr,
      totalCr,
    };
  }

  if (!env.SPECIALIST_RECONCILIATION_URL) {
    return { ok: false, error: "SPECIALIST_RECONCILIATION_URL not configured on Mark" };
  }
  if (!env.HUB_API_KEY) {
    return { ok: false, error: "HUB_API_KEY not configured on Mark" };
  }

  const url = `${env.SPECIALIST_RECONCILIATION_URL.replace(/\/$/, "")}/api/journals/draft`;
  let resp: Response;
  try {
    resp = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${env.HUB_API_KEY}`,
        "x-triggered-by": args.triggeredBy,
      },
      body: JSON.stringify({ entity, narration, date, lineAmountTypes, lines }),
    });
  } catch (e) {
    return { ok: false, error: `failed to reach reconciliation agent: ${e instanceof Error ? e.message : String(e)}` };
  }

  const json = await resp.json().catch(() => ({}));
  if (!resp.ok) {
    return {
      ok: false,
      error: (json as { error?: string }).error ?? `recon returned HTTP ${resp.status}`,
      totalDr,
      totalCr,
    };
  }

  const ok = json as { manualJournalId?: string; xeroLink?: string; writeLogId?: string };
  return {
    ok: true,
    manualJournalId: ok.manualJournalId,
    xeroLink: ok.xeroLink,
    writeLogId: ok.writeLogId,
    triggeredBy: args.triggeredBy,
    totalDr,
    totalCr,
  };
}
