// Send Tony a PAYG-due email when payroll DRAFTs are successfully posted.
//
// Ported (almost verbatim) from jbc-compliance/src/lib/payroll-payg-email.ts.
// Two separate ATO obligations — DO NOT combine totals on screen or in the
// email. SC tenant is a Large Withholder (weekly remittance). CQ tenant is
// its own legal entity with its own remittance schedule.
//
// Sends via the same SES path Mark's briefs use (lib/email.ts is already
// wired). We do NOT use sendChannelEmail() because the PAYG email isn't a
// brief — it's transactional. We call SES directly here with the same client.

import { SESv2Client, SendEmailCommand } from "@aws-sdk/client-sesv2";
import { env } from "@/lib/env";

const ses = new SESv2Client({
  region: env.AWS_REGION,
  credentials:
    env.AWS_ACCESS_KEY_ID && env.AWS_SECRET_ACCESS_KEY
      ? { accessKeyId: env.AWS_ACCESS_KEY_ID, secretAccessKey: env.AWS_SECRET_ACCESS_KEY }
      : undefined,
});

// ATO Payment Reference Numbers (PRNs) per entity — copy into pay.com / BPAY.
const ATO_PRN_SC = process.env.ATO_PRN_SC || "501614548607470";
const ATO_PRN_CQ = process.env.ATO_PRN_CQ || ""; // Tony to provide

const TONY_EMAIL = process.env.PAYG_EMAIL_RECIPIENT || "tony.sandy@justbettercare.com";

const FROM_ADDRESS = (() => {
  const domain = process.env.SES_FROM_DOMAIN || "justbettercareqld.com.au";
  return `JBC Payroll <payroll@${domain}>`;
})();

const aud = (n: number) =>
  new Intl.NumberFormat("en-AU", {
    style: "currency",
    currency: "AUD",
    minimumFractionDigits: 2,
  }).format(n);

export type PaygSide = {
  payg: number;
  superSg: number;
  netPay: number;
  totalDr: number;
  journalId: string;
  xeroLink: string;
  runs: string[];
};

export type PaygEmailOpts = {
  payPeriodFrom: string; // YYYY-MM-DD
  payPeriodTo: string;
  journalDate: string;
  sc: PaygSide | null;
  cq: PaygSide | null;
};

export type PaygEmailResult = { sent: boolean; skippedReason?: string };

export async function sendPaygEmail(opts: PaygEmailOpts): Promise<PaygEmailResult> {
  if (!env.AWS_ACCESS_KEY_ID || !env.AWS_SECRET_ACCESS_KEY) {
    return { sent: false, skippedReason: "SES not configured" };
  }
  if (!opts.sc && !opts.cq) {
    return { sent: false, skippedReason: "no SC or CQ side to report" };
  }

  const subject = `PAYG due — week ending ${opts.payPeriodTo}`;

  // Plain text — the THREE bits Tony needs front-and-centre per entity.
  const lines: string[] = [];
  lines.push(`Payroll DRAFTs posted for week ending ${opts.payPeriodTo}.`);
  lines.push("");
  lines.push("=== PAYG to pay at pay.com / BPAY (two SEPARATE entities) ===");
  lines.push("");
  if (opts.sc) {
    lines.push(`SC + WB (Sunshine Coast Pty Ltd — Large Withholder)`);
    lines.push(`  AMOUNT:    ${aud(opts.sc.payg)}`);
    lines.push(`  WEEK END:  ${opts.payPeriodTo}`);
    lines.push(`  PRN:       ${ATO_PRN_SC || "(set ATO_PRN_SC env var)"}`);
    lines.push("");
  }
  if (opts.cq) {
    lines.push(`CQ (Just Better Care CQ Pty Ltd — separate entity)`);
    lines.push(`  AMOUNT:    ${aud(opts.cq.payg)}`);
    lines.push(`  WEEK END:  ${opts.payPeriodTo}`);
    lines.push(`  PRN:       ${ATO_PRN_CQ || "(set ATO_PRN_CQ env var — Tony to provide)"}`);
    lines.push("");
  }
  lines.push("=== Journal details ===");
  if (opts.sc) {
    lines.push(`SC + WB — Employer super ${aud(opts.sc.superSg)} · Net pay ${aud(opts.sc.netPay)} · Total ${aud(opts.sc.totalDr)}`);
    lines.push(`  Runs: ${opts.sc.runs.join(", ")}`);
    lines.push(`  Xero DRAFT: ${opts.sc.xeroLink}`);
  }
  if (opts.cq) {
    lines.push(`CQ — Employer super ${aud(opts.cq.superSg)} · Net pay ${aud(opts.cq.netPay)} · Total ${aud(opts.cq.totalDr)}`);
    lines.push(`  Runs: ${opts.cq.runs.join(", ")}`);
    lines.push(`  Xero DRAFT: ${opts.cq.xeroLink}`);
  }
  lines.push("");
  lines.push(`Journal date: ${opts.journalDate}`);
  lines.push("Review both DRAFTs in Xero, then click Post when ready.");
  lines.push("");
  lines.push("— Mark (auto-generated by /payroll-journal)");
  const bodyText = lines.join("\n");

  // HTML version — the three pay.com fields huge and copy-friendly.
  const payRow = (label: string, value: string, mono = false) => `
    <tr>
      <td style="padding:4px 12px 4px 0;color:#475569;font-size:12px;width:80px">${label}</td>
      <td style="padding:4px 0;font-size:${mono ? 16 : 22}px;font-weight:600;color:#0f172a;${mono ? "font-family:ui-monospace,SFMono-Regular,Menlo,monospace;" : "font-variant-numeric:tabular-nums;"}user-select:all">${value}</td>
    </tr>`;

  const cardSc = opts.sc
    ? `
      <div style="background:#fffbeb;border:1px solid #fcd34d;border-radius:8px;padding:18px;margin:12px 0">
        <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.06em;color:#92400e;font-weight:600;margin-bottom:10px">
          SC + WB · Sunshine Coast Pty Ltd · Large Withholder
        </div>
        <table style="border-collapse:collapse">
          ${payRow("AMOUNT", aud(opts.sc.payg))}
          ${payRow("WEEK END", opts.payPeriodTo, true)}
          ${payRow("PRN", ATO_PRN_SC || "(set ATO_PRN_SC env)", true)}
        </table>
        <div style="margin-top:12px;font-size:12px;color:#78350f;border-top:1px solid #fde68a;padding-top:8px">
          Super ${aud(opts.sc.superSg)} · Net ${aud(opts.sc.netPay)} · Total ${aud(opts.sc.totalDr)} · Runs <span style="font-family:monospace">${opts.sc.runs.join(", ")}</span>
        </div>
        <div style="margin-top:6px"><a href="${opts.sc.xeroLink}" style="color:#a16207;font-weight:600;font-size:13px">Open SC DRAFT in Xero →</a></div>
      </div>`
    : "";

  const cardCq = opts.cq
    ? `
      <div style="background:#f0f9ff;border:1px solid #7dd3fc;border-radius:8px;padding:18px;margin:12px 0">
        <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.06em;color:#075985;font-weight:600;margin-bottom:10px">
          CQ · Just Better Care CQ Pty Ltd · separate entity
        </div>
        <table style="border-collapse:collapse">
          ${payRow("AMOUNT", aud(opts.cq.payg))}
          ${payRow("WEEK END", opts.payPeriodTo, true)}
          ${payRow("PRN", ATO_PRN_CQ || "(awaiting CQ PRN — set ATO_PRN_CQ env)", true)}
        </table>
        <div style="margin-top:12px;font-size:12px;color:#0c4a6e;border-top:1px solid #bae6fd;padding-top:8px">
          Super ${aud(opts.cq.superSg)} · Net ${aud(opts.cq.netPay)} · Total ${aud(opts.cq.totalDr)} · Runs <span style="font-family:monospace">${opts.cq.runs.join(", ")}</span>
        </div>
        <div style="margin-top:6px"><a href="${opts.cq.xeroLink}" style="color:#0369a1;font-weight:600;font-size:13px">Open CQ DRAFT in Xero →</a></div>
      </div>`
    : "";

  const bodyHtml = `
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;color:#0f172a">
      <h2 style="font-size:18px;margin:0 0 4px">Payroll DRAFTs posted — PAYG to pay</h2>
      <p style="color:#64748b;font-size:13px;margin:0 0 16px">
        Pay period <strong>${opts.payPeriodFrom} → ${opts.payPeriodTo}</strong> · journal date ${opts.journalDate}
      </p>
      <p style="color:#475569;font-size:13px;margin:0 0 12px">
        Copy AMOUNT + WEEK END + PRN into pay.com for each entity. SC and CQ are <strong>separate ATO obligations</strong>.
      </p>
      ${cardSc}
      ${cardCq}
      <p style="font-size:11px;color:#94a3b8;margin-top:24px">
        Auto-generated by /payroll-journal in Mark. Both Xero DRAFTs await your review + Post.
      </p>
    </div>
  `;

  try {
    await ses.send(
      new SendEmailCommand({
        FromEmailAddress: FROM_ADDRESS,
        Destination: { ToAddresses: [TONY_EMAIL] },
        Content: {
          Simple: {
            Subject: { Data: subject, Charset: "UTF-8" },
            Body: {
              Text: { Data: bodyText, Charset: "UTF-8" },
              Html: { Data: bodyHtml, Charset: "UTF-8" },
            },
          },
        },
      }),
    );
    return { sent: true };
  } catch (e) {
    return { sent: false, skippedReason: e instanceof Error ? e.message : String(e) };
  }
}
