// Parse data/chart-of-accounts/{sc,cq}.csv -> lib/chart-of-accounts.generated.ts
//
// Source of truth lives in the CSVs (raw Xero exports). To refresh after a
// chart change in Xero: re-export, drop the new CSVs in place, run
// `npm run build:chart`, commit both the CSV and the generated TS.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

interface RawRow {
  code: string;
  name: string;
  type: string;
  taxCode: string;
  description: string;
}

// Minimal RFC-4180 CSV parser. xlsx package could do this but pulling it in
// for one file felt like overkill.
function parseCsv(text: string): RawRow[] {
  const rows: string[][] = [];
  let field = "";
  let row: string[] = [];
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inQuotes) {
      if (ch === '"' && text[i + 1] === '"') {
        field += '"';
        i++;
      } else if (ch === '"') {
        inQuotes = false;
      } else {
        field += ch;
      }
    } else {
      if (ch === '"') inQuotes = true;
      else if (ch === ",") {
        row.push(field);
        field = "";
      } else if (ch === "\n" || ch === "\r") {
        if (field.length > 0 || row.length > 0) {
          row.push(field);
          rows.push(row);
          row = [];
          field = "";
        }
        if (ch === "\r" && text[i + 1] === "\n") i++;
      } else {
        field += ch;
      }
    }
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  // First row is the header.
  return rows.slice(1).map((r) => ({
    code: (r[0] || "").trim(),
    name: (r[1] || "").trim(),
    type: (r[2] || "").trim(),
    taxCode: (r[3] || "").trim(),
    description: (r[4] || "").trim(),
  }));
}

// Drop placeholder / "do not use" / templated rows that finance never posts to.
// Bank accounts have no code in the export — we keep them when they carry a real
// code (e.g. 1432 Westpac NDIS) and drop the unnumbered ones.
function isPostable(row: RawRow): boolean {
  if (!row.code) return false;
  const n = row.name;
  if (!n) return false;
  if (n.includes("DO NOT USE")) return false;
  if (n.startsWith("Do not Use") || row.description?.startsWith("Do not Use")) return false;
  if (/^Ben \d - /.test(n)) return false;
  if (n.includes('"HP NAME')) return false;
  if (n.includes('Asset "desc')) return false;
  if (/"Desc\d?"/.test(n)) return false;
  if (n.includes('"Entity Name')) return false;
  if (/^Bank Account \d+$/.test(n)) return false;
  if (/^Term Deposit( \d+)?$/.test(n)) return false;
  if (/^Distribution of Profit\d+$/.test(n)) return false;
  if (/^Opening Balance \d{3}$/.test(n)) return false;
  if (/^Owner Funds Introduced \d{3}$/.test(n)) return false;
  if (/^Owner Drawings \d{3}/.test(n)) return false;
  if (/^Share of Profit \d{3}$/.test(n)) return false;
  return true;
}

function shortTax(tax: string): string {
  return tax
    .replace(/^GST on Income$/, "GST inc")
    .replace(/^GST Free Income$/, "GST-free inc")
    .replace(/^GST on Expenses$/, "GST exp")
    .replace(/^GST Free Expenses$/, "GST-free exp")
    .replace(/^BAS Excluded$/, "BAS excl");
}

const ROOT = process.cwd();
const SC_CSV = readFileSync(join(ROOT, "data/chart-of-accounts/sc.csv"), "utf8");
const CQ_CSV = readFileSync(join(ROOT, "data/chart-of-accounts/cq.csv"), "utf8");

const sc = parseCsv(SC_CSV);
const cq = parseCsv(CQ_CSV);

const scPostable = sc.filter(isPostable);
const cqPostable = cq.filter(isPostable);

const generated = `// AUTO-GENERATED by scripts/build-chart.ts from data/chart-of-accounts/*.csv.
// Do not edit by hand. To refresh: re-export the chart from Xero, replace the
// CSV under data/chart-of-accounts/, and run \`npm run build:chart\`.

export interface AccountRow {
  code: string;
  name: string;
  type: string;
  taxCode: string;
  description: string;
}

export const SC_ACCOUNTS: AccountRow[] = ${JSON.stringify(scPostable, null, 2)};

export const CQ_ACCOUNTS: AccountRow[] = ${JSON.stringify(cqPostable, null, 2)};

export const SC_ACCOUNT_COUNT_RAW = ${sc.length};
export const CQ_ACCOUNT_COUNT_RAW = ${cq.length};
`;

const outPath = join(ROOT, "lib/chart-of-accounts.generated.ts");
writeFileSync(outPath, generated);

console.log(
  `[build-chart] SC: ${scPostable.length}/${sc.length} postable, ` +
    `CQ: ${cqPostable.length}/${cq.length} postable -> ${outPath}`,
);

function shortTaxLabel(t: string): string {
  return shortTax(t);
}
void shortTaxLabel;
